version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: equation
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_DATABASE: equation
      DB_PORT: 3306
    # links:
    #   - db
  frontend:
    build: ./Numer-react
    ports:
     - "3000:3000"
    depends_on:
      - backend